Complete homework 6
MrKekMan04/java-course-2023 pull request #10
Opened 2023-11-14 13:21 UTC by MrKekMan04

2023-12-10 11:03 UTC, Keindel requested changes

2023-12-10 11:03 UTC, Keindel commented on src/main/java/edu/hw6/task5/HackerNews.java
> +        } catch (URISyntaxException | InterruptedException | IOException ignored) {
логировать

2023-12-10 15:05 UTC, MrKekMan04 commented on src/main/java/edu/hw6/task2/Task2.java
> +            try (FileInputStream fileInputStream = new FileInputStream(from);
![image](https://github.com/MrKekMan04/java-course-2023/assets/87753891/39cb0fd0-b903-41b1-b1a5-f415ba81befa)

2023-12-11 13:24 UTC, Keindel approved these changes

2023-12-11 14:20 UTC, merged