Complete homework 2
MrKekMan04/java-course-2023 pull request #5
Opened 2023-10-16 13:34 UTC by MrKekMan04

2023-10-19 18:40 UTC, kkkoltunov requested changes
молодец, хорошая работа! общее замечание: старайся не использовать var, это усложняет читаемость кода и считается не самой лучшей практикой при работе в команде, используй var только в циклах

2023-10-19 18:40 UTC, kkkoltunov commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +public class PopularCommandExecutor {
unused класс?

2023-10-19 18:40 UTC, kkkoltunov commented on src/test/java/edu/hw2/task1/Task1Test.java
> +    public void constantTest() {
давай стараться именовать тесты в таком стиле `testThat...Returned...` чтобы по названию метода было понятно что происходит

поправить нужно **везде**

2023-10-20 18:00 UTC, MrKekMan04 commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +public class PopularCommandExecutor {
Нет. Но добавил к нему пару тестов.

2023-10-20 18:01 UTC, MrKekMan04 commented on src/test/java/edu/hw2/task1/Task1Test.java
> +    public void constantTest() {
Окей, исправил

2023-10-20 18:03 UTC, MrKekMan04 commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +public class PopularCommandExecutor {
На счёт `var` - хорошо, не буду использовать. Осталась привычка использовать неявное указание типа после шарпов

2023-10-24 07:30 UTC, merged