Complete homework 3
MrKekMan04/java-course-2023 pull request #6
Opened 2023-10-23 17:14 UTC by MrKekMan04

2023-11-05 22:19 UTC, Keindel requested changes

2023-11-05 22:19 UTC, Keindel commented on src/main/java/edu/hw3/task5/Task5.java
> +            .collect(Collectors.toCollection(ArrayList::new));
можно просто Collectors.toList()

2023-11-05 22:19 UTC, Keindel commented on src/main/java/edu/hw3/task5/Task5.java
> +        ArrayList<Person> result = contacts.stream().map(contact -> {
на мой взгляд result лучше называть именно результат, здесь лучше подойдет persons

2023-11-05 22:19 UTC, Keindel commented on src/main/java/edu/hw3/task5/Task5.java
> +    public static Collection<Person> parseContacts(Collection<String> contacts, String sortBy) {
В данном методе происходит сразу несколько разных задач.
Лучше декомпозировать на части. Например: getSortOrder(), parseContacts(), sortPersons().

2023-11-06 20:08 UTC, Keindel approved these changes
Оставил 1 комментарий. Работу принимаю.)

2023-11-06 20:08 UTC, Keindel commented on src/main/java/edu/hw3/task5/Person.java
> +            : o.surname.isEmpty() ? this.surname.compareTo(o.name) : this.surname.compareTo(o.surname);
Лаконично.) В будущем я бы посоветовал сместить акцент на упрощение восприятия, пусть даже за счет многословности. Сейчас можно не переделывать.

2023-11-06 20:12 UTC, MrKekMan04 commented on src/main/java/edu/hw3/task5/Person.java
> +            : o.surname.isEmpty() ? this.surname.compareTo(o.name) : this.surname.compareTo(o.surname);
Учту это в дальнейшем, спасибо!

2023-11-06 20:13 UTC, merged