Complete homework 4
MrKekMan04/java-course-2023 pull request #8
Opened 2023-10-30 17:29 UTC by MrKekMan04

2023-11-11 21:26 UTC, Keindel requested changes

2023-11-11 21:26 UTC, Keindel commented on src/main/java/edu/hw4/Task2.java
> +            .sorted(Comparator.comparingInt(Animal::weight).reversed())
выбрать к первых

2023-11-11 21:26 UTC, Keindel commented on src/main/java/edu/hw4/Task5.java
> +        return animals.stream()
👍

2023-11-11 21:26 UTC, Keindel commented on src/main/java/edu/hw4/Task6.java
> +        return animals.stream()
попробуй конструкцию вида
```
Collectors.toMap(
            Animal::type,
            Function.identity(),
            BinaryOperator.maxBy
```

2023-11-11 21:26 UTC, Keindel commented on src/main/java/edu/hw4/Task7.java
> +            .max(Comparator.comparingInt(Animal::age))
к-тое

2023-11-11 21:26 UTC, Keindel commented on src/main/java/edu/hw4/Task9.java
> +            .reduce(0, (counter, animal) -> counter + animal.paws(), Integer::sum);
`.mapToInt(Animal::paws).sum()`

2023-11-11 21:26 UTC, Keindel commented on src/main/java/edu/hw4/Task11.java
> +            .filter(animal -> animal.bites() && animal.height() <= MAX_HEIGHT)
рост которых превышает

2023-11-11 21:26 UTC, Keindel commented on src/main/java/edu/hw4/Task13.java
> +            .filter(animal -> animal.name().split(" ").length >= 2)
проверь строку `"     word"`

2023-11-11 21:26 UTC, Keindel commented on src/main/java/edu/hw4/Task17.java
> +            .filter(animal -> (animal.type() == Animal.Type.SPIDER || animal.type() == Animal.Type.DOG)
для читаемости лучше сделать несколько filter, чем много условий в одном
выделить отдельно `filter(animal -> animal.bites())`

2023-11-11 21:26 UTC, Keindel commented on src/main/java/edu/hw4/Task18.java
> +            .map(animals -> animals.stream()
попробуй flatmap

2023-11-11 21:26 UTC, Keindel commented on src/main/java/edu/hw4/AnimalValidator.java
> +    public static List<ValidationError> validAnimal(Animal animal) {
назвать метод лучше validateAnimal или getValidationErrors

2023-11-13 10:50 UTC, MrKekMan04 commented on src/main/java/edu/hw4/Task6.java
> +        return animals.stream()
Спасибо за совет. Отличная конструкция!

2023-11-15 18:05 UTC, Keindel approved these changes

2023-11-15 18:13 UTC, merged